from typing import TextIO, Callable, Any, TypeVar, overload
from .logger import Logger

F = TypeVar("F", bound=Callable[..., Any])

class TYPES:
    onHold_up: str
    onHold_down: str
    onConnect: str
    onAction: str
    onListChange: str
    onConnectorChange: str
    onShutdown: str
    onBroadcast: str
    onSettingUpdate: str
    onNotificationOptionClicked: str
    shortConnectorIdNotification: str
    allMessage: str
    onError: str

class Client:

    TPHOST: str
    TPPORT: int
    RCV_BUFFER_SZ: int
    SND_BUFFER_SZ: int
    SOCK_EVENT_TO: float

    pluginId: str
    sleepPeriod: float
    autoClose: bool
    currentStates: dict[str, str]
    currentSettings: dict[str, object]
    choiceUpdateList: dict[str, list[str]]
    shortIdTracker: dict[str, str]

    log: Logger

    def __init__(
        self,
        pluginId: str,
        sleepPeriod: float = ...,
        autoClose: bool = ...,
        checkPluginId: bool = ...,
        updateStatesOnBroadcast: bool = ...,
        maxWorkers: int | None = ...,
        executor: object | None = ...,
        useNamespaceCallbacks: bool = ...,
        loggerName: str | None = ...,
        logLevel: str | int | None = ...,
        logStream: TextIO | None = ...,
        logFileName: str | None = ...,
    ) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self) -> bool: ...
    def setLogLevel(self, level: str | int | None) -> None: ...
    def setLogStream(self, stream: TextIO | None) -> None: ...
    def setLogFile(self, fileName: str | None) -> None: ...
    def send(self, data: object) -> None: ...
    def createState(
        self, stateId: str, description: str, value: str, parentGroup: str | None = ...
    ) -> None: ...
    def createStateMany(self, states: list[dict[str, str]]) -> None: ...
    def removeState(self, stateId: str, validateExists: bool = ...) -> None: ...
    def removeStateMany(self, states: list[str]) -> None: ...
    def stateUpdate(self, stateId: str, stateValue: str) -> None: ...
    def stateUpdateMany(self, states: list[dict[str, str]]) -> None: ...
    def getStatelist(self) -> dict[str, str]: ...
    def getSettinghistory(self) -> dict[str, object]: ...
    def choiceUpdate(self, choiceId: str, values: list[str]) -> None: ...
    def choiceUpdateSpecific(
        self, stateId: str, values: list[str], instanceId: str
    ) -> None: ...
    def settingUpdate(self, settingName: str, settingValue: object) -> None: ...
    def shortIdUpdate(self, shortId: str, connectorValue: int) -> None: ...
    def connectorUpdate(self, connectorId: str, connectorValue: int) -> None: ...
    def showNotification(
        self, notificationId: str, title: str, msg: str, options: list[dict[str, str]]
    ) -> None: ...
    def getChoiceUpdatelist(self) -> dict[str, list[str]]: ...
    def isActionBeingHeld(self, actionId: str) -> bool: ...
    def updateActionData(
        self, instanceId: str, stateId: str, minValue: object, maxValue: object
    ) -> None: ...
    @staticmethod
    def getActionDataValue(
        data: list[dict[str, object]], valueId: str | None = ...
    ) -> object | None: ...
    @overload
    def on(self, event: str) -> Callable[[F], F]: ...
    @overload
    def on(self, event: str, func: F) -> F: ...
    def on(self, event: str, func: F | None = ...) -> Callable[[F], F] | F: ...
