from json import JSONEncoder
from logging import Formatter, Handler, Logger as StdLogger
from logging.handlers import TimedRotatingFileHandler
from typing import Any, TextIO

class Logger:
    DEFAULT_FILE_HANDLER_OPTS: dict[str, object]
    DEFAULT_LOG_FORMATTER: Formatter

    logger: StdLogger
    formatter: Formatter
    fileHandler: TimedRotatingFileHandler | None
    streamHandler: Handler | None
    nullHandler: Handler | None

    def __init__(
        self,
        name: str | None = ...,
        level: str | int | None = ...,
        stream: TextIO | None = ...,
        filename: str | None = ...,
        logger: StdLogger | None = ...,
        formatter: Formatter = ...,
        fileHandlerOpts: dict[str, object] = ...,
    ) -> None: ...
    def setLogLevel(
        self, level: str | int | None, logger: StdLogger | None = ...
    ) -> None: ...
    def setStreamDestination(self, stream: TextIO | None) -> None: ...
    def setFileDestination(
        self, filename: str | None, handlerOpts: dict[str, object] = ...
    ) -> None: ...
    def log(self, level: int, msg: object, *args: object, **kwargs: object) -> None: ...
    def debug(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def dbg(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def info(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def inf(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def warning(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def warn(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def wrn(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def error(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def err(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def critical(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def fatal(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def crt(self, msg: object, *args: object, **kwargs: object) -> None: ...
    def exception(self, msg: object, *args: object, **kwargs: object) -> None: ...

    class JsonEncoder(JSONEncoder):
        def default(self, o: Any) -> Any: ...

    @staticmethod
    def format_json(data: Any, indent: int = ...) -> str: ...
